### ISSUE TITLE
Version issue with configurable-http-proxy

### ISSUE THREAD

**Issue by tliebscherSAG** [pbutenee/ml-tutorial#5]
When I try to run docker build, I  get the following error:

 > [ 3/10] RUN npm install -g configurable-http-proxy:
#5 5.834 WARN engine prom-client@13.1.0: wanted: {"node":">=10"} (current: {"node":"8.10.0","npm":"3.5.2"})
#5 6.270 npm ERR! Linux 5.4.72-microsoft-standard-WSL2
#5 6.270 npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "configurable-http-proxy"
#5 6.271 npm ERR! node v8.10.0
#5 6.272 npm ERR! npm  v3.5.2

The problem is, that configurable-http-proxy needs npm >= 10, while in the docker container there ist version 8.

It works with configurable-http-proxy 4.2.3

**Comment by tliebscherSAG** [comment]
Ok, I take it back. It runs further but stops here now:

#7 121.1   Downloading https://files.pythonhosted.org/packages/9b/77/461087a514d2e8ece1c975d8216bc03f7048e6090c5166bc34115afdaa53/cryptography-3.4.7.tar.gz (546kB)
#7 122.6     Complete output from command python setup.py egg_info:
#7 122.6
#7 122.6             =============================DEBUG ASSISTANCE==========================
#7 122.6             If you are seeing an error here please try the following to
#7 122.6             successfully install cryptography:
#7 122.6
#7 122.6             Upgrade to the latest pip and try again. This will fix errors for most
#7 122.6             users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
#7 122.6             =============================DEBUG ASSISTANCE==========================
#7 122.6
#7 122.6     Traceback (most recent call last):
#7 122.6       File "<string>", line 1, in <module>
#7 122.6       File "/tmp/pip-build-y79wdm76/cryptography/setup.py", line 14, in <module>
#7 122.6         from setuptools_rust import RustExtension
#7 122.6     ModuleNotFoundError: No module named 'setuptools_rust'
#7 122.6
#7 122.6     ----------------------------------------
#7 124.2 Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-y79wdm76/cryptography/

**Comment by pbutenee** [comment]
Thanks for bringing this up. It took me a while, but I managed to fix it. In case you are still interested, just let me know if you run into there issues and I'll promise I'll fix it sooner next time ;-)
